services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: supabase-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data:Z
      - ./init:/docker-entrypoint-initdb.d:Z
    networks:
      Servers:
        ipv4_address: 172.16.0.30
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-d", "postgres", "-U", "postgres"]
      timeout: 5s
      interval: 5s
      retries: 3

  # Supabase Auth service
  auth:
    image: supabase/gotrue:v2.132.3
    container_name: supabase-auth
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL:-http://172.16.0.33}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgresql://authenticator:${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}@172.16.0.30:5432/postgres
      GOTRUE_SITE_URL: ${SITE_URL:-http://172.16.0.33}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS:-}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP:-false}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY:-3600}
      GOTRUE_JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-token-with-at-least-32-characters-long}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP:-true}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM:-true}
    networks:
      Servers:
        ipv4_address: 172.16.0.31
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      timeout: 5s
      interval: 5s
      retries: 3

  # PostgREST API
  rest:
    image: postgrest/postgrest:v12.0.1
    container_name: supabase-rest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgresql://authenticator:${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}@172.16.0.30:5432/postgres
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-public,auth}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-token-with-at-least-32-characters-long}
      PGRST_DB_USE_LEGACY_GUCS: "false"
    command: postgrest
    networks:
      Servers:
        ipv4_address: 172.16.0.32
    restart: unless-stopped

  # Gateway/Proxy to expose services
  gateway:
    image: nginx:alpine
    container_name: supabase-gateway
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      auth:
        condition: service_healthy
      rest:
        condition: service_started
    networks:
      Servers:
        ipv4_address: 172.16.0.33

  # Supabase Studio - Web Interface for Management
  studio:
    image: supabase/studio:latest
    container_name: supabase-studio
    environment:
      - SUPABASE_URL=http://172.16.0.33
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTg4MTk0MzUsImlzcyI6InN1cGFiYXNlIiwiZXhwIjoyMDc0MzUyMjM1LCJyb2xlIjoiYW5vbiJ9.pg7IFMNQWCRTGRwpV_TwB21T2mMq6YubXYtWKr18wV8}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTg4MTk0MzUsImlzcyI6InN1cGFiYXNlIiwiZXhwIjoyMDc0MzUyMjM1LCJyb2xlIjoic2VydmljZV9yb2xlIn0.GKk3cYuD-Y1n-i0_V6iit7l7eI7hqFP-alCwIQv8QlU}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}
    depends_on:
      - gateway
    networks:
      Servers:
        ipv4_address: 172.16.0.34

networks:
  Servers:
    name: Servers
    external: true
