services:
  # API Backend
  backend:
    image: darkchannelagent-backend:latest
    build: ./backend
    container_name: darkchannelagent-backend
    environment:
      - NODE_ENV=production
      - PORT=8080
      - CORS_ORIGIN=http://localhost
      # Supabase (connects to Supabase services via external access)
      - SUPABASE_URL=${SUPABASE_URL:-http://host.docker.internal:54321}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # N8N
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_WEBHOOK_SCREENPLAY_URL=${N8N_WEBHOOK_SCREENPLAY_URL}
      - N8N_WEBHOOK_VIDEO_URL=${N8N_WEBHOOK_VIDEO_URL}
      - N8N_CALLBACK_SECRET=${N8N_CALLBACK_SECRET}
      # Payments
      - PAYMENT_PROVIDER=${PAYMENT_PROVIDER}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - CREDITS_PRICE_CENTS=${CREDITS_PRICE_CENTS:-3000}
      # Dev flags
      - ALLOW_ANON=${ALLOW_ANON:-false}
      - ALLOW_ANON_ADMIN=${ALLOW_ANON_ADMIN:-false}
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 20s
      timeout: 5s
      retries: 5

  # Web Frontend
  frontend:
    image: darkchannelagent-frontend:latest
    build: 
      context: ./frontend
      args:
        - VITE_SUPABASE_URL=${SUPABASE_URL_PUBLIC:-http://172.16.0.33:80}
        - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
        - VITE_API_BASE_URL=http://localhost:8080
    container_name: darkchannelagent-frontend
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL_PUBLIC:-http://172.16.0.33:80}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    expose:
      - "3000"

  # Nginx Proxy for external access
  proxy:
    image: nginx:alpine
    container_name: darkchannelagent-proxy
    ports:
      - "3000:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped



